export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const ADD_EMPLOYEES = 'ADD_EMPLOYEES';
export const GET_SINGLE_EMPLOYEES = 'GET_SINGLE_EMPLOYEES';
export const UPDATE_EMPLOYEES = 'UPDATE_EMPLOYEES';
export const DELETE_EMPLOYEES = 'DELETE_EMPLOYEES';
